In [4]:
#first we import numpy
import numpy as np


In [5]:
np.array([1,2,3])


array([1, 2, 3])

In [6]:
a = np.array([1,2,3])
print(a)
print(type(a))


[1 2 3]
<class 'numpy.ndarray'>


In [7]:
a.shape

(3,)

In [8]:
a = np.array([1,2,3,4,5,6])
a.reshape(2,3)


array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,8,9]
arr = np.array([my_lst1,my_lst2,my_lst3])
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [10]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,8,9]
arr = np.array([my_lst1,my_lst2,my_lst3])
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [11]:
arr
#why it shows array in output while when we print it dosen't show array

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [12]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [12]:
a[3]

np.int64(4)

In [13]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [14]:
arr[0:2, 0:2]

array([[1, 2],
       [2, 3]])

In [16]:
arr[1:,3:]
#row with index 1 and column with index 3

array([[5, 6],
       [8, 9]])

In [16]:
#in built functions in python
arr = np.arange(0,10)

In [17]:
arr = np.arange(0,10)

In [19]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
arr = np.arange(0,10,step =2)

In [22]:
print(arr)

[0 2 4 6 8]


In [25]:
np.linspace(1,10,50)
#20 random points we get by this

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [26]:
arr[3:]

array([6, 8])

In [27]:
arr[3:]=100

In [28]:
print(arr)

[  0   2   4 100 100]


In [29]:
a = 10
b = a
b = 20
print(a)
print(b)

10
20


In [30]:
a = np.array([1,2,3,4])

In [32]:
b = a
b[0] = 100
print(a)
print(b)
#here we see that changes in b will also affect chenges in a 

[100   2   3   4]
[100   2   3   4]


In [18]:
arr1 = arr.copy()
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
arr1 = arr.copy()
print(arr1)
#for copy of data 

[  0   2   4 100 100]


In [36]:
val = 2
arr<2

array([ True, False, False, False, False])

In [37]:
arr*2

array([  0,   4,   8, 200, 200])

In [38]:
arr[arr<2]

array([0])

In [39]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [40]:
np.ones(4)

array([1., 1., 1., 1.])

In [41]:
np.ones(8,dtype = int).reshape(4,2)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [42]:
np.ones((2,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [44]:
np.random.rand(3,3)
#takes values between 0 and 1 by normal distribution

array([[0.66208578, 0.89018658, 0.71130864],
       [0.55031583, 0.44426026, 0.72775325],
       [0.88963183, 0.01876775, 0.14741198]])

In [45]:
arr_ex = np.random.randn(4,4)

In [47]:
print(arr_ex)
#taking value as standard normal distribution

[[-1.4795251  -0.71733931  1.19119451 -1.44497073]
 [-1.69739563  1.75328647 -1.07196364 -0.65067365]
 [ 0.12867386 -1.6923778  -0.52699875 -1.74422442]
 [-1.55104978 -0.39079874  1.16025833 -1.07114575]]


In [39]:
np.random.randint(0,100,8).reshape(4,2)

array([[11, 16],
       [47, 55],
       [ 5, 22],
       [80, 83]], dtype=int32)

In [40]:
np.random.randint(0,100,8).reshape(4,2)

array([[95,  6],
       [32, 57],
       [50, 31],
       [ 8, 57]], dtype=int32)

In [34]:
np.random.random_sample((1,5))

array([[0.16727294, 0.34100504, 0.99598071, 0.7706218 , 0.06904395]])

In [35]:
np.random.randint(0,100,8).reshape(4,2)

array([[28, 35],
       [83, 35],
       [ 0, 40],
       [85, 87]], dtype=int32)